[package]
name = "osp-sim"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "osp-sim"
path = "src/main.rs"

[[bin]]
name = "mm-grades"
path = "src/bin/mm-grades.rs"

[[bin]]
name = "fesa-players"
path = "src/bin/fesa-players.rs"

[[bin]]
name = "fesa-dump"
path = "src/bin/fesa-dump.rs"

[[bin]]
name = "cup-detect"
path = "src/bin/cup-detect.rs"

[dependencies]
osp-core = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
rayon = "1"
clap = { version = "4", features = ["derive"] }
ureq = "2"
