#!/usr/bin/env python3
"""mm_study.py — drive a large-scale MacMahon-threshold study over a FESA corpus.

It compares a baseline Swiss config against MacMahon configs generated by
mm-grades at one or more group-size floors N and variants a/b/c:

    swiss                     basic Swiss (default settings, no MacMahon)
    n<N>a                     mm-grades thresholds only (static MacMahon)
    n<N>b                     + estimate-MM with a Flat unrated prior
    n<N>c                     + estimate-MM with the asymmetric Huber-Laplace prior

(mm-grades picks thresholds on grade boundaries so every group holds at least N
players.) Which Ns and letters to sweep is chosen per run via --ns / --letters;
the default `--ns 10 20 --letters a b c` is the original seven-config study.

The smallest N is the *gate*: a tournament whose field is too small for it is
skipped entirely. Larger Ns need progressively bigger fields, so each contributes
its configs only to the tournaments large enough — coverage shrinks as N grows,
and the config sets nest.

The study runs in two phases so the (expensive) simulation is never repeated
just to re-analyse:

    run      simulate every tournament, storing per-run dumps + a manifest;
    analyze  read the stored dumps and print one overall comparison.

Only `analyze` produces a report — there are no per-tournament reports. Every
metric comparison is *paired within a tournament* (the configs share common
random numbers per run) and then aggregated *across tournaments* (the independent
unit of replication). Each pair of configs is compared only on the tournaments
where both were run (its own n), so no two configs are ever compared over
different tournament sets. `analyze --filter unrated_noneu` restricts to
tournaments with an unrated player of a non-European nationality.

Usage:
    scripts/mm_study.py run     [--ns N... --letters a b c] [options]
    scripts/mm_study.py analyze [--out DIR] [--filter unrated_noneu]

Run `scripts/mm_study.py run -h` for the knobs (runs, seed, jitter, corpus,
season/file filters, --keep-going, --force, --no-build).
"""

import argparse
import collections
import csv
import json
import math
import os
import re
import shutil
import statistics
import subprocess
import sys
import time
from pathlib import Path

# ----------------------------------------------------------------------------
# Layout / constants
# ----------------------------------------------------------------------------

REPO = Path(__file__).resolve().parent.parent
DEFAULT_CORPUS = REPO / "test_files" / "fesa_results"
DEFAULT_OUT = REPO / "study_out"
INVALID_DIRNAME = "invalid"

# Config kinds are named `swiss` and `n<N><letter>` (e.g. `n10a`), where N is the
# mm-grades group-size floor and the letter is its variant. Which N values and
# letters to sweep is chosen per run (--ns / --letters); the baseline swiss is
# always included. mm-grades emits every variant, in this letter order.
MM_LETTERS = ["a", "b", "c", "d"]


def kind_name(n, letter):
    return "n{}{}".format(n, letter)


def kind_sort_key(kind):
    """Order kinds as: swiss first, then by N ascending (finer groups first), then
    by variant letter."""
    if kind == "swiss":
        return (0, 0, "")
    m = re.match(r"n(\d+)([a-z])$", kind)
    return (1, int(m.group(1)), m.group(2)) if m else (2, 0, kind)

# The dump columns (osp-sim --dump-runs), and which are "higher is better".
METRICS = [
    ("mean_diff", False, "mean|d| (ELO gap between paired opponents)"),
    ("frac_exceed", False, "P(|d|>400)"),
    ("fidelity", True, "standings fidelity (Spearman vs true strength)"),
    ("hit", True, "top-1 hit rate (winner is the truly-strongest player)"),
    ("interest", True, "interest(W) (game-interest welfare)"),
]
# mean_diff / frac_exceed also get a relative-Δ%, since their scale varies a lot
# across fields.
RELATIVE_METRICS = {"mean_diff", "frac_exceed"}


# ----------------------------------------------------------------------------
# Small helpers
# ----------------------------------------------------------------------------

def eprint(*a, **k):
    print(*a, file=sys.stderr, **k)
    sys.stderr.flush()


def bin_path(name):
    p = REPO / "target" / "release" / name
    return p


def season_dirs(corpus):
    """Every season subdirectory (sorted), excluding the invalid/ bucket."""
    out = []
    for entry in sorted(corpus.iterdir()):
        if entry.is_dir() and entry.name != INVALID_DIRNAME:
            out.append(entry)
    return out


def result_files(season):
    """The result files in a season dir (sorted), ignoring dotfiles/archives."""
    out = []
    for entry in sorted(season.iterdir()):
        if entry.is_file() and not entry.name.startswith(".") and entry.suffix != ".gz":
            out.append(entry)
    return out


# A round cell for an absent player is the opponent number `0` with a result
# sign: `0=` (scored a half point) or `0-` (scored nothing). These must be matched
# as whole tokens — a naive substring would count the `0=` inside `10=` (a draw
# against player 10). `(?<!\S)` anchors to a token start (after whitespace / line
# start), tolerating a trailing `(annotation)`; the negative digit-lookbehind on
# the `0` is redundant with that but harmless.
_ABSENT_HALF = re.compile(r"(?<!\S)0=")
_ABSENT_ZERO = re.compile(r"(?<!\S)0-")


def prefers_half_point_absences(result_file):
    """True when the file has strictly more half-point absences (`0=`) than
    zero-point ones (`0-`), i.e. its convention is that an absence scores ½. FESA
    tables are Latin-1; a byte value equals its code point, matching osp-core's
    decode_latin1."""
    text = result_file.read_text(encoding="latin-1")
    return len(_ABSENT_HALF.findall(text)) > len(_ABSENT_ZERO.findall(text))


def detect_cup(result_file):
    """(size, nation) when the file was run as a single-elimination cup among the
    top 2^N players of its most common nationality, else None. Delegates to
    cup-detect, which reuses osp-core's cup seeding + bracket replay, so a hit is a
    tournament osp-sim can reproduce as that hybrid cup. Raises on a tool failure."""
    proc = subprocess.run(
        [str(bin_path("cup-detect")), str(result_file)], capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise RuntimeError("cup-detect failed on {}:\n{}".format(result_file, proc.stderr.strip()))
    out = proc.stdout.strip()
    if not out:
        return None
    size, nation = out.split(",", 1)
    return int(size), nation


# ----------------------------------------------------------------------------
# run phase
# ----------------------------------------------------------------------------

def build_binaries():
    eprint("building osp-sim, mm-grades, fesa-players, cup-detect (release) ...")
    subprocess.run(
        ["cargo", "build", "--release", "--bin", "osp-sim", "--bin", "mm-grades",
         "--bin", "fesa-players", "--bin", "cup-detect"],
        cwd=REPO,
        check=True,
    )


def run_mm_grades(result_file, n, workdir):
    """Run mm-grades for one N into `workdir`; return (paths, info).

    `paths` is the list of the three generated JSON files (a, b, c) in order, or
    [] if mm-grades emitted nothing (field too small for N). `info` carries a few
    parsed facts (players, groups) for the manifest. Raises on a parse/tool
    failure so the caller can stop or record it.
    """
    workdir.mkdir(parents=True, exist_ok=True)
    proc = subprocess.run(
        [str(bin_path("mm-grades")), str(result_file), str(n), str(workdir)],
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        raise RuntimeError("mm-grades failed on {} (N={}):\n{}".format(result_file, n, proc.stderr.strip()))

    info = {"players": None, "groups": None}
    for line in proc.stderr.splitlines():
        # "107 players (102 rated, 5 unrated); N = 8; 8 threshold(s) -> 9 group(s):"
        if " players (" in line and "threshold(s)" in line:
            try:
                info["players"] = int(line.split(" players", 1)[0].strip())
                info["groups"] = int(line.split("-> ", 1)[1].split(" group", 1)[0])
            except (ValueError, IndexError):
                pass

    stem = result_file.stem
    expected = [workdir / "{}.mm{}-{}.json".format(stem, n, letter) for letter in MM_LETTERS]
    present = [p for p in expected if p.exists()]
    if present and len(present) != len(MM_LETTERS):
        raise RuntimeError("mm-grades produced a partial set for {} (N={}): {}".format(result_file, n, present))
    return present, info


def stage_configs(result_file, out, season, stem, ns, letters, keep_going):
    """Generate + stage all configs for one tournament under out/configs/... .

    `ns` is the ascending list of group-size floors to sweep; `letters` the mm-grades
    variants (subset of a/b/c/d). The smallest N is the *gate*: if it yields no
    thresholds the tournament is skipped entirely. Each larger N contributes its
    configs only when it too yields thresholds (a strictly bigger field is needed),
    so coverage shrinks as N grows.

    Returns (kinds, info): `kinds` is the ordered list of config-kind labels that
    were staged (always starts with "swiss"), empty when the tournament is skipped.
    On a tooling error it either raises (default) or returns info["error"]
    (keep_going).
    """
    cfg_dir = out / "configs" / season / stem
    if cfg_dir.exists():
        shutil.rmtree(cfg_dir)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    work = out / "_work" / season / stem
    if work.exists():
        shutil.rmtree(work)

    info = {"players": None, "groups": {}, "skip": None, "error": None, "half_abs": False, "cup": None}
    letter_idx = {l: i for i, l in enumerate(MM_LETTERS)}
    gate = ns[0]
    kinds = []

    for i, n in enumerate(ns):
        try:
            paths, ninfo = run_mm_grades(result_file, n, work / "n{}".format(n))
        except RuntimeError as e:
            if keep_going:
                info["error"] = str(e)
                return [], info
            raise
        if i == 0:
            info["players"] = ninfo["players"]
            if not paths:
                info["skip"] = "no_n{}".format(gate)  # gate empty -> skip entirely
                return [], info
            # First real N: set up the baseline, the file's absence convention, and
            # whether it was actually run as a cup (applied to the whole run below).
            info["half_abs"] = prefers_half_point_absences(result_file)
            try:
                info["cup"] = detect_cup(result_file)
            except RuntimeError as e:
                if keep_going:
                    info["error"] = str(e)
                    return [], info
                raise
            (cfg_dir / "swiss.json").write_text("{}\n")  # default == basic Swiss
            kinds.append("swiss")
        if not paths:
            continue  # this (larger) N doesn't apply to this field
        info["groups"][n] = ninfo["groups"]
        for letter in letters:
            label = kind_name(n, letter)
            shutil.copyfile(paths[letter_idx[letter]], cfg_dir / (label + ".json"))
            kinds.append(label)

    # Apply the file's absence convention to *all* staged configs uniformly, so
    # swiss and every MacMahon variant score this tournament's absences the same.
    if info["half_abs"]:
        for kind in kinds:
            cfg_file = cfg_dir / (kind + ".json")
            cfg = json.loads(cfg_file.read_text())
            cfg["half_point_absences"] = True
            cfg_file.write_text(json.dumps(cfg, indent=2) + "\n")

    shutil.rmtree(work, ignore_errors=True)
    return kinds, info


def run_osp_sim(result_file, cfg_dir, kinds, dump_path, cup, args):
    """Invoke osp-sim for one tournament, writing the per-run dump. When `cup` is
    (size, nation), the run reproduces the hybrid direct-elimination cup, so the
    cup rounds are bracket-paired rather than Swiss — the faithful format for a
    tournament that was actually a cup. Raises on failure (osp-sim's stderr)."""
    dump_path.parent.mkdir(parents=True, exist_ok=True)
    config_files = [str(cfg_dir / (k + ".json")) for k in kinds]
    cmd = [
        str(bin_path("osp-sim")),
        "--results", str(result_file),
        "--jitter", str(args.jitter),
        "--runs", str(args.runs),
        "--seed", str(args.seed),
        "--configs", *config_files,
        "--dump-runs", str(dump_path),
    ]
    if cup:
        size, nation = cup
        cmd += ["--cup-size", str(size), "--cup-nations", nation]
    proc = subprocess.run(cmd, capture_output=True, text=True)
    if proc.returncode != 0:
        raise RuntimeError("osp-sim failed on {}:\n{}".format(result_file, proc.stderr.strip()))


def phase_run(args):
    out = Path(args.out)
    corpus = Path(args.corpus)
    out.mkdir(parents=True, exist_ok=True)
    (out / "raw").mkdir(exist_ok=True)

    if not args.no_build:
        build_binaries()
    for name in ("osp-sim", "mm-grades"):
        if not bin_path(name).exists():
            eprint("error: missing binary {} (build it first)".format(bin_path(name)))
            return 1

    ns = sorted(set(args.ns))
    letters = [l for l in MM_LETTERS if l in set(args.letters)]  # canonical a,b,c order
    expected_full = 1 + len(ns) * len(letters)  # swiss + every (N, letter)

    # Persist the run parameters for provenance / reproducibility.
    meta = {
        "corpus": str(corpus),
        "runs": args.runs,
        "seed": args.seed,
        "jitter": args.jitter,
        "ns": ns,
        "letters": letters,
        "started": time.strftime("%Y-%m-%d %H:%M:%S"),
        "git_commit": _git_commit(),
    }
    (out / "meta.json").write_text(json.dumps(meta, indent=2) + "\n")

    manifest_path = out / "manifest.csv"
    new_manifest = not manifest_path.exists() or args.force
    manifest = open(manifest_path, "w" if new_manifest else "a", newline="")
    writer = csv.writer(manifest)
    if new_manifest:
        writer.writerow(
            ["season", "file", "stem", "status", "players", "n_configs", "configs", "half_abs", "cup", "error"]
        )

    seasons = season_dirs(corpus)
    if args.seasons:
        wanted = set(args.seasons)
        seasons = [s for s in seasons if s.name in wanted]

    totals = dict(files=0, run=0, full=0, partial=0, skipped=0, cached=0, errors=0, cups=0)
    t0 = time.time()

    for season in seasons:
        files = result_files(season)
        if args.max_files:
            files = files[: args.max_files]
        s = dict(files=0, run=0, full=0, partial=0, skipped=0, cached=0, errors=0, cups=0)

        for rf in files:
            stem = rf.stem
            totals["files"] += 1
            s["files"] += 1
            dump_path = out / "raw" / season.name / (stem + ".csv")

            # Resume: a non-empty dump already there means done (unless --force).
            if dump_path.exists() and dump_path.stat().st_size > 0 and not args.force:
                totals["cached"] += 1
                s["cached"] += 1
                continue

            try:
                kinds, info = stage_configs(rf, out, season.name, stem, ns, letters, args.keep_going)
            except RuntimeError as e:
                eprint("\nERROR (config generation): {}".format(e))
                eprint("stopping (use --keep-going to record and continue).")
                manifest.close()
                return 1

            players = info["players"] or ""
            cup_str = "{}:{}".format(*info["cup"]) if info.get("cup") else ""
            if info["error"]:
                writer.writerow([season.name, rf.name, stem, "error", players, 0, "", "", cup_str, info["error"].replace("\n", " ")])
                totals["errors"] += 1
                s["errors"] += 1
                continue

            if not kinds:  # skipped (gate N yielded no thresholds)
                writer.writerow([season.name, rf.name, stem, info["skip"], players, 0, "", "", cup_str, ""])
                totals["skipped"] += 1
                s["skipped"] += 1
                continue

            try:
                run_osp_sim(rf, out / "configs" / season.name / stem, kinds, dump_path, info["cup"], args)
            except RuntimeError as e:
                if args.keep_going:
                    writer.writerow([season.name, rf.name, stem, "error", players, len(kinds), "|".join(kinds), int(info["half_abs"]), cup_str, str(e).replace("\n", " ")])
                    totals["errors"] += 1
                    s["errors"] += 1
                    continue
                eprint("\nERROR (osp-sim): {}".format(e))
                eprint("stopping (use --keep-going to record and continue).")
                manifest.close()
                return 1

            writer.writerow([
                season.name, rf.name, stem, "run", players, len(kinds), "|".join(kinds), int(info["half_abs"]), cup_str, "",
            ])
            totals["run"] += 1
            s["run"] += 1
            if cup_str:
                totals["cups"] += 1
                s["cups"] += 1
            full = len(kinds) == expected_full
            key = "full" if full else "partial"
            totals[key] += 1
            s[key] += 1
            manifest.flush()

        eprint(
            "[{season}] {files} files -> {run} run ({full} full, {partial} partial), "
            "{skipped} skipped, {cached} cached{cup}{err}".format(
                season=season.name, files=s["files"], run=s["run"], full=s["full"],
                partial=s["partial"], skipped=s["skipped"], cached=s["cached"],
                cup="" if not s["cups"] else ", {} cup".format(s["cups"]),
                err="" if not s["errors"] else ", {} ERRORS".format(s["errors"]),
            )
        )

    manifest.close()
    dt = time.time() - t0
    eprint("\n=== run complete in {:.0f}s ===".format(dt))
    eprint("sweep             : Ns={} letters={} (full = {} configs)".format(ns, letters, expected_full))
    eprint("files seen        : {}".format(totals["files"]))
    eprint("simulated         : {}  ({} full, {} partial)".format(totals["run"], totals["full"], totals["partial"]))
    eprint("skipped (gate N)  : {}".format(totals["skipped"]))
    eprint("cached (resumed)  : {}".format(totals["cached"]))
    eprint("cups detected     : {}  (run as hybrid direct-elimination cups)".format(totals["cups"]))
    eprint("errors            : {}".format(totals["errors"]))
    eprint("raw dumps + manifest under {}".format(out))
    return 0


def _git_commit():
    try:
        return subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True
        ).stdout.strip()
    except Exception:
        return None


# ----------------------------------------------------------------------------
# analyze phase
# ----------------------------------------------------------------------------

# European nationality codes (ISO-3166-1 alpha-2, generous: includes Russia, the
# Caucasus, Turkey — consistent with the FESA/European shogi scene). A player's
# nationality is "non-European" for this study if it's a plausible 2-letter code
# not in here (a 3-letter junk code like "PRO", or a blank, does not qualify).
EUROPEAN = frozenset(
    "AD AL AM AT AZ BA BE BG BY CH CY CZ DE DK EE ES FI FO FR GB GE GG GI GR HR "
    "HU IE IM IS IT JE LI LT LU LV MC MD ME MK MT NL NO PL PT RO RS RU SE SI SK "
    "SM TR UA VA XK".split()
)


def _is_non_european(nat):
    return len(nat) == 2 and nat not in EUROPEAN


def _manifest_file_map(out):
    """(season, stem) -> original result filename, from the manifest."""
    m = {}
    path = Path(out) / "manifest.csv"
    if path.exists():
        with open(path, newline="") as fh:
            for row in csv.DictReader(fh):
                m[(row["season"], row["stem"])] = row["file"]
    return m


def compute_tournament_tags(out, corpus, refresh=False):
    """Per-tournament tags derived from the result files (parsed via fesa-players):
    whether it has any unrated player, and the set of non-European nationalities
    among its unrated players. Cached to tournament_tags.json so repeated analyses
    don't re-parse the corpus."""
    cache = Path(out) / "tournament_tags.json"
    if cache.exists() and not refresh:
        return json.loads(cache.read_text())

    fmap = _manifest_file_map(out)
    corpus = Path(corpus)
    tags = {}
    raw = Path(out) / "raw"
    missing = 0
    for csv_path in sorted(raw.rglob("*.csv")):
        season, stem = csv_path.parent.name, csv_path.stem
        key = "{}/{}".format(season, stem)
        fname = fmap.get((season, stem), stem + ".txt")
        rf = corpus / season / fname
        if not rf.exists():
            missing += 1
            continue
        proc = subprocess.run([str(bin_path("fesa-players")), str(rf)], capture_output=True, text=True)
        if proc.returncode != 0:
            missing += 1
            continue
        has_unrated = False
        noneu = set()
        for line in proc.stdout.splitlines()[1:]:
            nat, rated = line.rsplit(",", 1)
            if rated == "0":
                has_unrated = True
                if _is_non_european(nat):
                    noneu.add(nat)
        tags[key] = {"has_unrated": has_unrated, "unrated_noneu_nats": sorted(noneu)}
    if missing:
        eprint("warning: {} tournament(s) could not be tagged (result file missing/unparsed)".format(missing))
    cache.write_text(json.dumps(tags, indent=2) + "\n")
    return tags


def load_tournament_means(out):
    """Read every raw dump; return {tournament_key: {kind: {metric: run_mean}}}.

    The run-mean collapses each config's 1000 CRN-paired runs to one number per
    metric — the tournament is the unit of replication for cross-tournament
    aggregation.
    """
    raw = Path(out) / "raw"
    table = {}
    for csv_path in sorted(raw.rglob("*.csv")):
        key = "{}/{}".format(csv_path.parent.name, csv_path.stem)
        sums = {}   # kind -> metric -> [sum, count]
        with open(csv_path, newline="") as fh:
            reader = csv.DictReader(fh)
            for row in reader:
                kind = row["variant"]
                acc = sums.setdefault(kind, {m: [0.0, 0] for m, _, _ in METRICS})
                for m, _, _ in METRICS:
                    acc[m][0] += float(row[m])
                    acc[m][1] += 1
        means = {}
        for kind, macc in sums.items():
            means[kind] = {m: (macc[m][0] / macc[m][1] if macc[m][1] else float("nan")) for m, _, _ in METRICS}
        if means:
            table[key] = means
    return table


def paired_stats(pairs, higher_better):
    """Paired A/B stats over tournaments. `pairs` is a list of (a, b) per-tournament
    means (both configs present). Returns a dict with the mean difference (b-a),
    its 95% CI half-width, a z (normal approx), a distribution-free sign-test, and
    a mean relative difference. `higher_better` orients "favours b"."""
    diffs = [b - a for a, b in pairs]
    rels = [(b - a) / a for a, b in pairs if a not in (0.0,)]
    n = len(diffs)
    mean = statistics.fmean(diffs)
    if n >= 2:
        sd = statistics.stdev(diffs)
        se = sd / math.sqrt(n)
    else:
        sd = se = 0.0
    z = mean / se if se > 0 else 0.0
    # "favour b": improvement in the metric's good direction.
    fav = sum(1 for d in diffs if (d > 0) == higher_better and d != 0)
    unfav = sum(1 for d in diffs if (d < 0) == higher_better and d != 0)
    return {
        "n": n,
        "mean": mean,
        "ci": 1.959964 * se,
        "z": z,
        "stars": _stars(z),
        "median": statistics.median(diffs),
        "rel_mean": (statistics.fmean(rels) if rels else float("nan")),
        "fav": fav,
        "unfav": unfav,
        "sign_p": _sign_test_p(fav, unfav),
    }


def _stars(z):
    a = abs(z)
    if a >= 3.290527:
        return "***"
    if a >= 2.575829:
        return "**"
    if a >= 1.959964:
        return "*"
    return "ns"


def _sign_test_p(fav, unfav):
    """Two-sided exact binomial sign-test p-value for `fav` successes out of
    `fav+unfav` at p=0.5. All-integer until the final ratio so it stays exact for
    large n (float `2.0**n` overflows past n≈1024)."""
    n = fav + unfav
    if n == 0:
        return 1.0
    k = min(fav, unfav)
    tail = sum(math.comb(n, i) for i in range(0, k + 1)) / (2 ** n)  # int/int -> float, no overflow
    return min(1.0, 2.0 * tail)


def _intersection_pairs(table, a, b, metric):
    """(a, b) per-tournament means for every tournament that has *both* configs."""
    return [(t[a][metric], t[b][metric]) for t in table.values() if a in t and b in t]


def _fmt_delta(st, metric):
    rel = ""
    if metric in RELATIVE_METRICS and not math.isnan(st["rel_mean"]):
        rel = "  ({:+.1f}%)".format(100.0 * st["rel_mean"])
    return "n={:<4} {:+.3f} ±{:.3f} {:<3}{}  [favour {}/{}, sign p={:.1e}]".format(
        st["n"], st["mean"], st["ci"], st["stars"], rel, st["fav"], st["fav"] + st["unfav"], st["sign_p"]
    )


def _cmp(table, a, b, metric, higher):
    return paired_stats(_intersection_pairs(table, a, b, metric), higher)


def _report_metric_block(table, baseline, others, pairs):
    """Per-metric comparisons: each non-baseline kind vs the baseline (on their own
    support), then the requested among-others pairs. Every comparison is paired on
    exactly the tournaments where both configs are present (its own n)."""
    for m, higher, desc in METRICS:
        print()
        print("  Δ {}  [{}; {} is better]".format(m, desc, "higher" if higher else "lower"))
        for kind in others:
            print("    {:<6} vs {:<6}: {}".format(kind, baseline, _fmt_delta(_cmp(table, baseline, kind, m, higher), m)))
        for (a, b) in pairs:
            if a in others and b in others:
                print("    {:<6} vs {:<6}: {}".format(b, a, _fmt_delta(_cmp(table, a, b, m, higher), m)))


def phase_analyze(args):
    out = Path(args.out)
    if not (out / "raw").exists():
        eprint("no raw/ under {} — run the `run` phase first".format(out))
        return 1

    table = load_tournament_means(out)
    if not table:
        eprint("no dumps found under {}/raw".format(out))
        return 1

    # Corpus recap from the manifest (if present) plus what actually loaded.
    print("MacMahon-threshold study — overall comparison")
    meta_path = out / "meta.json"
    corpus = None
    if meta_path.exists():
        meta = json.loads(meta_path.read_text())
        corpus = meta.get("corpus")
        print("  runs={runs}  seed={seed}  jitter={jitter}  corpus={corpus}".format(**meta))
        if meta.get("git_commit"):
            print("  git commit: {}".format(meta["git_commit"]))
    _print_manifest_recap(out)

    # Optional subset filter (needs the corpus to re-parse player nationalities).
    if args.filter == "unrated_noneu":
        if not corpus:
            eprint("cannot filter: meta.json has no corpus path")
            return 1
        tags = compute_tournament_tags(out, corpus, refresh=args.refresh_tags)
        kept = {k: v for k, v in table.items() if tags.get(k, {}).get("unrated_noneu_nats")}
        nat_counts = collections.Counter()
        for k in kept:
            for nat in tags[k]["unrated_noneu_nats"]:
                nat_counts[nat] += 1
        print()
        print("  FILTER: only tournaments with >=1 unrated player of a non-European nationality")
        print("  matched {} of {} simulated tournaments".format(len(kept), len(table)))
        print("  non-European unrated nationalities present (tournaments each):")
        print("    " + ", ".join("{}:{}".format(n, c) for n, c in nat_counts.most_common()))
        table = kept
        if not table:
            eprint("no tournaments match the filter")
            return 1

    # Discover the config kinds actually present, ordered swiss, then finer→coarser.
    kinds = sorted({k for t in table.values() for k in t}, key=kind_sort_key)
    baseline = "swiss" if "swiss" in kinds else kinds[0]
    others = [k for k in kinds if k != baseline]
    support = {k: sum(1 for t in table.values() if k in t) for k in kinds}
    common = [key for key, t in table.items() if all(k in t for k in kinds)]

    print()
    print("  configs present (tournaments each): "
          + ", ".join("{}:{}".format(k, support[k]) for k in kinds))
    print("  common support (all configs present): {} tournaments".format(len(common)))
    print("  Δ = mean over tournaments of (config − other) per-tournament run-mean;")
    print("  each comparison is paired on its own intersection (n shown); ±95% CI")
    print("  (normal approx); stars from |z|; sign p = two-sided sign test.")

    # Descriptive within-common-block mean levels (equal weight per tournament).
    if common:
        print()
        print("  mean levels on the {} common tournaments (equal weight):".format(len(common)))
        print("    {:<6}".format("config") + "".join("{:>16}".format(m) for m, _, _ in METRICS))
        for kind in kinds:
            vals = [statistics.fmean(table[k][kind][m] for k in common) for m, _, _ in METRICS]
            print("    {:<6}".format(kind) + "".join("{:>16.4f}".format(v) for v in vals))

    # All adjacent + spanning pairs among the non-baseline kinds (finer vs coarser).
    among = [(others[i], others[j]) for i in range(len(others)) for j in range(i + 1, len(others))]
    print()
    print("=" * 78)
    print("COMPARISON — each vs {}, then finer-vs-coarser among the rest".format(baseline))
    _report_metric_block(table, baseline, others, among)

    print()
    print("Notes: tournament is the unit of replication (runs within one share common")
    print("random numbers, so are not independent). Each pair is compared only on")
    print("tournaments where both configs exist — coverage grows as the group floor N")
    print("shrinks, so smaller-N configs carry larger n against the baseline.")
    return 0


def _print_manifest_recap(out):
    path = Path(out) / "manifest.csv"
    if not path.exists():
        return
    run = skipped = errors = 0
    ncfg = collections.Counter()
    with open(path, newline="") as fh:
        for row in csv.DictReader(fh):
            st = row["status"]
            if st == "run":
                run += 1
                ncfg[row["n_configs"]] += 1
            elif st == "error":
                errors += 1
            else:  # skipped_no_n<gate>
                skipped += 1
    dist = ", ".join("{}×{}cfg".format(c, n) for n, c in sorted(ncfg.items(), key=lambda x: -int(x[0] or 0)))
    print("  manifest: {} simulated ({}), {} skipped, {} errors".format(run, dist, skipped, errors))


# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------

def main(argv):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)

    r = sub.add_parser("run", help="simulate the corpus and store raw results")
    r.add_argument("--corpus", default=str(DEFAULT_CORPUS), help="corpus root (default: %(default)s)")
    r.add_argument("--out", default=str(DEFAULT_OUT), help="output dir for raw dumps + manifest (default: %(default)s)")
    r.add_argument("--runs", type=int, default=1000, help="osp-sim runs per config (default: %(default)s)")
    r.add_argument("--seed", type=int, default=0, help="osp-sim master seed (default: %(default)s)")
    r.add_argument("--jitter", type=float, default=1.0, help="osp-sim --jitter (default: %(default)s)")
    r.add_argument("--ns", type=int, nargs="+", default=[10, 20],
                   help="MacMahon group-size floors to sweep; smallest is the skip gate (default: 10 20)")
    r.add_argument("--letters", nargs="+", choices=MM_LETTERS, default=MM_LETTERS,
                   help="mm-grades variants to stage per N (default: a b c)")
    r.add_argument("--seasons", nargs="+", help="only these season dir names (default: all)")
    r.add_argument("--max-files", type=int, help="cap files per season (for smoke tests)")
    r.add_argument("--keep-going", action="store_true", help="record tool errors and continue instead of stopping")
    r.add_argument("--force", action="store_true", help="re-run tournaments even if a dump already exists")
    r.add_argument("--no-build", action="store_true", help="skip the cargo build step")

    a = sub.add_parser("analyze", help="print the overall comparison from stored raw results")
    a.add_argument("--out", default=str(DEFAULT_OUT), help="dir with raw dumps + manifest (default: %(default)s)")
    a.add_argument(
        "--filter", choices=["all", "unrated_noneu"], default="all",
        help="restrict to a tournament subset: 'unrated_noneu' = has >=1 unrated player of a "
        "non-European nationality (default: all)",
    )
    a.add_argument("--refresh-tags", action="store_true", help="recompute cached per-tournament tags (re-parse the corpus)")

    args = ap.parse_args(argv)
    if args.cmd == "run":
        return phase_run(args)
    if args.cmd == "analyze":
        return phase_analyze(args)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
