[package]
name = "osp-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
integer-blossom = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
thiserror = { workspace = true }
ts-rs = { workspace = true }
derive_more = { workspace = true }
rand = { workspace = true }
rand_chacha = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
